---
- name:               Build APIC Configuration from Scratch
  hosts:              apic1
  connection:         local
  gather_facts:       no
  
  tasks:
    - name: Interface Selectors
      import_tasks: tasks/interface_selectors.yaml