---
- name:               Build APIC Configuration from Scratch
  hosts:              apic1
  connection:         local
  gather_facts:       no
  
  tasks:
    - name: VRF, BD, EPG, Tenant
      import_tasks: tasks/vrf_bd_epg.yaml