---
- name: Create Link Level Policies
  aci_rest:
    host: "{{ apic_info.host }}"
    username: "{{ apic_info.username }}"
    password: "{{ apic_info.password }}"
    validate_certs: no
    use_proxy: no
    path: /api/mo/uni/infra.json
    method: post
    content:
      fabricHIfPol:
        attributes:
          dn: "uni/infra/hintfpol-{{ item.name }}"
          rn: "hintfpol-{{ item.name }}"
          name: "{{ item.name }}"
          speed: "{{ item.speed }}"
          descr: "{{ shared_vars.descr }}"
          status: "{{ 'deleted' if (state | default('present')) == 'absent' else 'created,modified' }}"
  with_items: "{{ link_level_policies }}"
