bdSubnets:
- bdName: BD-5G-ILO-3901
  gwAddress: 2405:200:1410:1444:f9::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-OAM-3902
  gwAddress: 2405:200:1410:1444:fa::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-SIGNALLING-3903
  gwAddress: 2405:200:1410:1444:fb::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-EMS-3904
  gwAddress: 2405:200:1410:1444:fc::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-DB-CLIENT-3905
  gwAddress: 2405:200:1410:1444:fd::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-DB-SERVER-3906
  gwAddress: 2405:200:1410:1444:fe::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-HEARTBEAT-3907
  gwAddress: 2405:200:1410:1444:ff::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-REPLICATION-3908
  gwAddress: 2405:200:1410:1444:100::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-PROVISIONING-3909
  gwAddress: 2405:200:1410:1444:101::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-INTERNAL-COMMUNICATION-3910
  gwAddress: 2405:200:1410:1444:102::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-SIGTRAN-A-3911
  gwAddress: 2405:200:1410:1444:103::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-SIGTRAN-B-3912
  gwAddress: 2405:200:1410:1444:104::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-DIAMETER-3913
  gwAddress: 2405:200:1410:1444:105::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-GLOBAL-3914
  gwAddress: 2405:200:1410:1444:106::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-LCS-CLIENT-3915
  gwAddress: 2405:200:1410:1444:107::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-LI-X1-PROVISIONING-3916
  gwAddress: 2405:200:1410:1444:108::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-LI-X2-PROVISIONING-3917
  gwAddress: 2405:200:1410:1444:109::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-LI-SIGNALING-3918
  gwAddress: 2405:200:1410:1444:10a::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-N2-3919
  gwAddress: 2405:200:1410:1444:10b::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-GTP-3920
  gwAddress: 2405:200:1410:1444:10c::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-PFCP-3921
  gwAddress: 2405:200:1410:1444:10d::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-PFCP-SIGNALLING-3922
  gwAddress: 2405:200:1410:1444:10e::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-N3-LOOPBACK-3923
  gwAddress: 2405:200:1410:1444:10f::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-N3-INTERFACE-3924
  gwAddress: 2405:200:1410:1444:110::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-N6-DATA-3925
  gwAddress: 2405:200:1410:1444:111::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-N6-VOICE-3926
  gwAddress: 2405:200:1410:1444:112::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-X3-DATA-3927
  gwAddress: 2405:200:1410:1444:113::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-SMF-ASBC-3928
  gwAddress: 2405:200:1410:1444:114::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-PCF-PROV-3929
  gwAddress: 2405:200:1410:1444:115::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-N9-LOOPBACK-3932
  gwAddress: 2405:200:1410:1444:116::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-N9-INTERFACE-3930
  gwAddress: 2405:200:1410:1444:117::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
- bdName: BD-5G-IPDR-IPV6-3949
  gwAddress: 2405:200:1410:1444:118::1
  mask: 80
  tenantName: TELCO-DC-JMNGR-001
