bridgeDomains:
- bdName: BD-5G-ILO-3901
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-OSS-NOC-MGMT
- bdName: BD-5G-OAM-3902
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-MGMT
- bdName: BD-5G-SIGNALLING-3903
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-EMS-3904
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-MGMT
- bdName: BD-5G-DB-CLIENT-3905
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-DB-SERVER-3906
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-HEARTBEAT-3907
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-REPLICATION-3908
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-PROVISIONING-3909
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-INTERNAL-COMMUNICATION-3910
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-SIGTRAN-A-3911
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-WLS-CORE-SIGNALLING
- bdName: BD-5G-SIGTRAN-B-3912
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-WLS-CORE-SIGNALLING
- bdName: BD-5G-DIAMETER-3913
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-WLS-CORE-SIGNALLING
- bdName: BD-5G-GLOBAL-3914
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-GLOBAL
- bdName: BD-5G-LCS-CLIENT-3915
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-LI-X1-PROVISIONING-3916
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-LI-X2-PROVISIONING-3917
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-LI-SIGNALING-3918
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-N2-3919
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-GNB-SIGNALING
- bdName: BD-5G-GTP-3920
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-WLS-CORE-SIGNALLING
- bdName: BD-5G-PFCP-3921
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-PFCP-SIGNALLING-3922
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-N3-LOOPBACK-3923
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-GNB-BEARER
- bdName: BD-5G-N3-INTERFACE-3924
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-GNB-BEARER
- bdName: BD-5G-N6-DATA-3925
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-DATA-SUBSCRIBER
- bdName: BD-5G-N6-VOICE-3926
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-VOICE-SUBSCRIBER
- bdName: BD-5G-X3-DATA-3927
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-CORE-SIGNALLING
- bdName: BD-5G-SMF-ASBC-3928
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-5G-VOICE-SUBSCRIBER
- bdName: BD-5G-PCF-PROV-3929
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-WLS-CORE-SIGNALLING
- bdName: BD-5G-N9-LOOPBACK-3932
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-GNB-BEARER
- bdName: BD-5G-N9-INTERFACE-3930
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL-GNB-BEARER
- bdName: BD-5G-IPDR-IPV6-3949
  tenantName: TELCO-DC-JMNGR-001
  vrfName: RJIL_IP_MGMT
