epgs:
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-ILO-3901
  epgName: EPG-5G-ILO-3901
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-OAM-3902
  epgName: EPG-5G-OAM-3902
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-SIGNALLING-3903
  epgName: EPG-5G-SIGNALLING-3903
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-EMS-3904
  epgName: EPG-5G-EMS-3904
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-DB-CLIENT-3905
  epgName: EPG-5G-DB-CLIENT-3905
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-DB-SERVER-3906
  epgName: EPG-5G-DB-SERVER-3906
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-HEARTBEAT-3907
  epgName: EPG-5G-HEARTBEAT-3907
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-REPLICATION-3908
  epgName: EPG-5G-REPLICATION-3908
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-PROVISIONING-3909
  epgName: EPG-5G-PROVISIONING-3909
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-INTERNAL-COMMUNICATION-3910
  epgName: EPG-5G-INTERNAL-COMMUNICATION-3910
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-SIGTRAN-A-3911
  epgName: EPG-5G-SIGTRAN-A-3911
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-SIGTRAN-B-3912
  epgName: EPG-5G-SIGTRAN-B-3912
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-DIAMETER-3913
  epgName: EPG-5G-DIAMETER-3913
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-GLOBAL-3914
  epgName: EPG-5G-GLOBAL-3914
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-LCS-CLIENT-3915
  epgName: EPG-5G-LCS-CLIENT-3915
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-LI-X1-PROVISIONING-3916
  epgName: EPG-5G-LI-X1-PROVISIONING-3916
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-LI-X2-PROVISIONING-3917
  epgName: EPG-5G-LI-X2-PROVISIONING-3917
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-LI-SIGNALING-3918
  epgName: EPG-5G-LI-SIGNALING-3918
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-N2-3919
  epgName: EPG-5G-N2-3919
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-GTP-3920
  epgName: EPG-5G-GTP-3920
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-PFCP-3921
  epgName: EPG-5G-PFCP-3921
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-PFCP-SIGNALLING-3922
  epgName: EPG-5G-PFCP-SIGNALLING-3922
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-N3-LOOPBACK-3923
  epgName: EPG-5G-N3-LOOPBACK-3923
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-N3-INTERFACE-3924
  epgName: EPG-5G-N3-INTERFACE-3924
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-N6-DATA-3925
  epgName: EPG-5G-N6-DATA-3925
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-N6-VOICE-3926
  epgName: EPG-5G-N6-VOICE-3926
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-X3-DATA-3927
  epgName: EPG-5G-X3-DATA-3927
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-SMF-ASBC-3928
  epgName: EPG-5G-SMF-ASBC-3928
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-PCF-PROV-3929
  epgName: EPG-5G-PCF-PROV-3929
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-N9-LOOPBACK-3932
  epgName: EPG-5G-N9-LOOPBACK-3932
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-N9-INTERFACE-3930
  epgName: EPG-5G-N9-INTERFACE-3930
  tenantName: TELCO-DC-JMNGR-001
- apName: AP-5G-EPC-CORE
  bdName: BD-5G-IPDR-IPV6-3949
  epgName: EPG-5G-IPDR-IPV6-3949
  tenantName: TELCO-DC-JMNGR-001
