swPolicyLeafProfiles:
  - swPolicyLeafProfileName: Leaf-203
    leafName: Leaf-203
    leafId: '203'
  - swPolicyLeafProfileName: Leaf-253
    leafName: Leaf-253
    leafId: '253'
  - swPolicyLeafProfileName: Leaf-204
    leafName: Leaf-204
    leafId: '204'
  - swPolicyLeafProfileName: Leaf-254
    leafName: Leaf-254
    leafId: '254'
  - swPolicyLeafProfileName: Leaf-1401
    leafName: Leaf-1401
    leafId: '1401'
  - swPolicyLeafProfileName: Leaf-1402
    leafName: Leaf-1402
    leafId: '1402'
  - swPolicyLeafProfileName: Leaf-1403
    leafName: Leaf-1403
    leafId: '1403'
  - swPolicyLeafProfileName: Leaf-1404
    leafName: Leaf-1404
    leafId: '1404'
  - swPolicyLeafProfileName: Leaf-1405
    leafName: Leaf-1405
    leafId: '1405'
  - swPolicyLeafProfileName: Leaf-1406
    leafName: Leaf-1406
    leafId: '1406'
  - swPolicyLeafProfileName: Leaf-1407
    leafName: Leaf-1407
    leafId: '1407'
  - swPolicyLeafProfileName: Leaf-1408
    leafName: Leaf-1408
    leafId: '1408'
  - swPolicyLeafProfileName: Leaf-1409
    leafName: Leaf-1409
    leafId: '1409'
  - swPolicyLeafProfileName: Leaf-1410
    leafName: Leaf-1410
    leafId: '1410'
  - swPolicyLeafProfileName: Leaf-1451
    leafName: Leaf-1451
    leafId: '1451'
  - swPolicyLeafProfileName: Leaf-1452
    leafName: Leaf-1452
    leafId: '1452'
  - swPolicyLeafProfileName: Leaf-1453
    leafName: Leaf-1453
    leafId: '1453'
  - swPolicyLeafProfileName: Leaf-1454
    leafName: Leaf-1454
    leafId: '1454'
  - swPolicyLeafProfileName: Leaf-1455
    leafName: Leaf-1455
    leafId: '1455'
  - swPolicyLeafProfileName: Leaf-1456
    leafName: Leaf-1456
    leafId: '1456'
  - swPolicyLeafProfileName: Leaf-1457
    leafName: Leaf-1457
    leafId: '1457'
